name: Build Release

on:
  release:
    types:
    - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: microsoft
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Build with Gradle
      run: './gradlew build --no-daemon'
    
    - name: Publish
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        version-type: release

        # Comment this line out if you do *not* want your release jars automatically attached to the GitHub release.
        github-token: ${{ secrets.GITHUB_TOKEN }}

        # Uncomment these lines if you want automatic releasing on CurseForge. You will need to add a CurseForge token in repository settings.
        #  DO NOT PUT YOUR TOKEN IN THIS FILE
    #     curseforge-id: 0
    #     curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

        # Uncomment these lines if you want automatic releasing on Modrinth. You will need to add a Modrinth token in repository settings.
        #  DO NOT PUT YOUR TOKEN IN THIS FILE
    #    modrinth-id: 0
    #    modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
